version: "3.9"
services:
  cardano-producer: # block-producer node
    image: arradev/cardano-pool:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: cardano-producer
    networks:
      - cardano
    volumes:
      - $PWD/config/local/:/config
    env_file:
      - producer.env
   command: --start --staking 
    restart: always
    depends_on: 
      - cardano-relay
  cardano-relay: # relay node
    image: arradev/cardano-pool:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: cardano-relay
    networks:
      - cardano
    volumes:
      - $PWD/config/local/:/config
    env_file:
      - relay.env
    command: --start
    restart: always

networks:
  cardano:
    name: cardano
